name: Build check
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  macos_build_job:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        run: brew install soapysdr
      - name: Build
        run: |
          cmake -B build
          cmake --build build

  linux_build_job:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup tools
        run: |
          sudo apt-get update -q -y
          sudo apt-get install -y --no-install-recommends cmake ninja-build
          sudo apt-get install -q -y libsoapysdr-dev
      - name: Build
        run: |
          cmake -GNinja -B build
          cmake --build build
